apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-migrate.yaml
  - schema-reconcile.yaml
  - vertex-bootstrap.yaml

configMapGenerator:
  - name: manifest-vertex-bootstrap
    files:
      - vertex-bootstrap.js

generatorOptions:
  disableNameSuffixHash: true
