apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/andreybotkin/llm-gateway
    newTag: main
  - name: ghcr.io/andreybotkin/llm-gateway/vertex-token-refresh
    newTag: main
