apiVersion: v1
kind: Service
metadata:
  name: manifest
  labels:
    app.kubernetes.io/name: manifest
    app.kubernetes.io/part-of: platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: manifest
  ports:
    - name: http
      port: 2099
      targetPort: http
      protocol: TCP
